name: "Sementic Versioning"
description: "Calculate and output sementic version"
inputs:
    value-type:
        description: return value type, one of current | nextpatch | nextminor | nextmajor
        default: current
        required: false
    github-token:
        description: The GitHub token used to create an authenticated client
        default: ${{ github.token }}
        required: false
outputs:
    value:
        description: "value version, ex) v1.2.3 => v1.2.3"
    value-nopatch:
        description: "value minor version, ex) v1.2.3 => v1.2"
    value-nominor:
        description: "value major version, ex) v1.2.3 => v1"
    current:
        description: "current version, ex) v1.2.3 => v1.2.3"
    current-nopatch:
        description: "current minor version, ex) v1.2.3 => v1.2"
    current-nominor:
        description: "current major version, ex) v1.2.3 => v1"
    nextpatch:
        description: "next patch version, ex) v1.2.3 => v1.2.4"
    nextpatch-nopatch:
        description: "next patch version, ex) v1.2.3 => v1.2"
    nextpatch-nominor:
        description: "next patch version, ex) v1.2.3 => v1"
    nextminor:
        description: "next minor version, ex) v1.2.3 => v1.3.0"
    nextminor-nopatch:
        description: "next minor version, ex) v1.2.3 => v1.3"
    nextminor-nominor:
        description: "next minor version, ex) v1.2.3 => v1"
    nextmajor:
        description: "next major version, ex) v1.2.3 => v2.0.0"
    nextmajor-nopatch:
        description: "next major version, ex) v1.2.3 => v2.0"
    nextmajor-nominor:
        description: "next major version, ex) v1.2.3 => v2"
runs:
    using: "node16"
    main: "lib/index.js"
