name: Release

on:
    workflow_dispatch:
        inputs:
            type:
                type: choice
                required: true
                default: next-patch
                description: "Versioning type"
                options:
                    - "nextpatch"
                    - "nextminor"
                    - "nextmajor"
            email:
                type: string
                required: true
                description: "Release user email"
            title:
                type: string
                default: Auto Release
                description: "Release title"
            body:
                type: string
                default: Github Action auto released
                description: "Release body"

jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Guess semver
              id: semver
              uses: egoavara/semver@v0.0.5
              with:
                  value-type: ${{ inputs.type }}
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.semver.outputs.value }}
                  release_name: "Release ${{ steps.semver.outputs.value }} : ${{ github.event.inputs.title }}"
                  body: ${{ github.event.inputs.body }}
            - uses: rickstaa/action-create-tag@v1
              with:
                  tag: "latest"
                  tag_exists_error: false
                  message: "Latest release"
            - uses: rickstaa/action-create-tag@v1
              with:
                  tag: "${{steps.semver.outputs.value-nominor}}"
                  tag_exists_error: false
                  message: "Latest release"
            - uses: rickstaa/action-create-tag@v1
              with:
                  tag: "${{steps.semver.outputs.value-nopatch}}"
                  tag_exists_error: false
                  message: "Latest release"
